<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2m69-gcr7-jv3q" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SporcuGelisim.Domain\SporcuGelisim.Domain.csproj" />
    <ProjectReference Include="..\..\src\SporcuGelisim.Application\SporcuGelisim.Application.csproj" />
    <ProjectReference Include="..\..\src\SporcuGelisim.Infrastructure\SporcuGelisim.Infrastructure.csproj" />
  </ItemGroup>

</Project>
